#nombre de la app y puerto en el que corre
spring.application.name=sismos
server.port=8080

#configuracion conexion a mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/redsismica?allowPublicKeyRetrieval=true&useSSL=false   #nombre de la bd 
spring.datasource.username=root
spring.datasource.password=root

# Esto asegura que se creen o actualicen las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Para inicializar el esquema con scripts
spring.datasource.initialization-mode=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
path_cross=http://localhost:5173
path_mapping=api/v1